import { z } from "zod";

/**
 * Schema for client.config.ts. The config is the only source for pages, SEO,
 * redirects, form recipients and business details. A config that fails this
 * schema fails the build. The studio setup script validates with the same
 * schema before creating anything.
 */

const path = z
  .string()
  .regex(/^\/([a-z0-9-]+(\/[a-z0-9-]+)*)?$/, "Use lowercase paths like /about or /services/audits");

const page = z.object({
  path,
  navLabel: z.string().min(1),
  inNav: z.boolean().default(true),
  inFooter: z.boolean().default(false),
  seoTitle: z.string().min(1).max(70),
  description: z.string().min(50).max(170),
  ogImageText: z.string().optional(),
});

const formField = z.object({
  name: z.string().regex(/^[a-z][a-zA-Z0-9]*$/, "camelCase field names only"),
  label: z.string().min(1),
  type: z.enum(["text", "email", "tel", "textarea", "select"]),
  required: z.boolean().default(false),
  maxLength: z.number().int().positive().max(5000).optional(),
  options: z.array(z.string()).optional(),
});

const directive = z.enum([
  "script-src",
  "style-src",
  "img-src",
  "font-src",
  "connect-src",
  "frame-src",
  "media-src",
  "form-action",
]);

export const clientConfigSchema = z
  .object({
    slug: z.string().regex(/^[a-z0-9-]+$/),
    business: z.object({
      tradingName: z.string().min(1),
      legalName: z.string().min(1),
      companyNumber: z.string().optional(),
      registeredAddress: z.string().min(1),
      email: z.email(),
      phone: z.string().optional(),
      icoNumber: z.string().optional(),
    }),
    domain: z.object({
      apex: z.string().regex(/^[a-z0-9-]+(\.[a-z0-9-]+)+$/, "Domain only, no https:// or www."),
      canonical: z.enum(["apex", "www"]).default("www"),
      dnsOnVercel: z.boolean().default(false),
    }),
    pages: z.array(page).min(1),
    redirects: z
      .array(
        z.object({
          from: z.string().startsWith("/"),
          to: z.string().startsWith("/"),
          permanent: z.boolean().default(true),
        }),
      )
      .default([]),
    form: z.object({
      page: path,
      recipients: z.array(z.email()).min(1),
      fields: z.array(formField).min(1),
      successMessage: z.string().min(1),
      autoReply: z.boolean().default(false),
    }),
    analytics: z
      .object({
        gtmId: z
          .string()
          .regex(/^GTM-[A-Z0-9]+$/)
          .optional(),
        existingGa4Id: z
          .string()
          .regex(/^G-[A-Z0-9]+$/)
          .optional(),
      })
      .default({}),
    socials: z.record(z.string(), z.url()).default({}),
    seo: z.object({
      schemaType: z.enum(["Organization", "LocalBusiness"]).default("Organization"),
      defaultOgText: z.string().optional(),
    }),
    legal: z.object({
      lastUpdated: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
    }),
    care: z
      .object({
        reportTo: z.array(z.email()).default([]),
      })
      .default({ reportTo: [] }),
    csp: z.partialRecord(directive, z.array(z.string())).default({}),
    copyLint: z
      .object({
        allow: z.array(z.string()).default([]),
      })
      .default({ allow: [] }),
  })
  .superRefine((cfg, ctx) => {
    const paths = cfg.pages.map((p) => p.path);
    if (!paths.includes("/")) {
      ctx.addIssue({ code: "custom", path: ["pages"], message: "A home page with path / is required" });
    }
    const dupes = paths.filter((p, i) => paths.indexOf(p) !== i);
    if (dupes.length) {
      ctx.addIssue({ code: "custom", path: ["pages"], message: `Duplicate page paths: ${dupes.join(", ")}` });
    }
    for (const reserved of ["/privacy", "/terms"]) {
      if (paths.includes(reserved)) {
        ctx.addIssue({ code: "custom", path: ["pages"], message: `${reserved} is generated by the template; remove it from pages` });
      }
    }
    if (!paths.includes(cfg.form.page)) {
      ctx.addIssue({ code: "custom", path: ["form", "page"], message: `form.page ${cfg.form.page} is not in pages` });
    }
    const email = cfg.form.fields.find((f) => f.name === "email");
    if (!email || email.type !== "email" || !email.required) {
      ctx.addIssue({ code: "custom", path: ["form", "fields"], message: "The form needs a required field named email of type email" });
    }
    cfg.form.fields.forEach((f, i) => {
      if (f.type === "select" && !f.options?.length) {
        ctx.addIssue({ code: "custom", path: ["form", "fields", i], message: "select fields need options" });
      }
    });
  });

export type ClientConfigInput = z.input<typeof clientConfigSchema>;
export type ClientConfig = z.output<typeof clientConfigSchema>;
export type PageConfig = ClientConfig["pages"][number];
export type FormField = ClientConfig["form"]["fields"][number];

/** Typed helper for client.config.ts. Validation happens in lib/config.ts. */
export function defineConfig(config: ClientConfigInput): ClientConfigInput {
  return config;
}
