import raw from "../client.config";
import { HONEYPOT_FIELD, type PublicForm } from "./form";
import { clientConfigSchema, type ClientConfig, type PageConfig } from "./config.schema";

function load(): ClientConfig {
  const result = clientConfigSchema.safeParse(raw);
  if (!result.success) {
    const issues = result.error.issues.map((i) => `  - ${i.path.join(".") || "(root)"}: ${i.message}`).join("\n");
    throw new Error(`client.config.ts is invalid:\n${issues}`);
  }
  return result.data;
}

export const config = load();

export const siteUrl = `https://${config.domain.canonical === "www" ? "www." : ""}${config.domain.apex}`;

/** Pages generated by the template rather than listed in the config. */
export const legalPages: PageConfig[] = [
  {
    path: "/privacy",
    navLabel: "Privacy",
    inNav: false,
    inFooter: true,
    seoTitle: `Privacy notice | ${config.business.tradingName}`,
    description: `How ${config.business.legalName} collects, uses and protects personal information through this website.`,
  },
  {
    path: "/terms",
    navLabel: "Terms",
    inNav: false,
    inFooter: true,
    seoTitle: `Website terms | ${config.business.tradingName}`,
    description: `The terms that apply when you use the ${config.business.tradingName} website, set out in plain English.`,
  },
];

/** Every page on the site: config pages in nav order, then the legal pages. */
export const allPages: PageConfig[] = [...config.pages, ...legalPages];

export const navPages = config.pages.filter((p) => p.inNav);
export const footerPages = allPages.filter((p) => p.inFooter);

export function getPage(path: string): PageConfig | undefined {
  return allPages.find((p) => p.path === path);
}

/** True only on the live production deployment. Previews and local builds are never indexed. */
export const isProduction = process.env.VERCEL_ENV === "production";

/** Form details safe to hand to the client-side form. */
export const publicForm: PublicForm = {
  fields: config.form.fields,
  successMessage: config.form.successMessage,
  honeypotField: HONEYPOT_FIELD,
};
