/**
 * ThumbStop copy rules, enforced by scripts/copy-lint.ts on the rendered site.
 * Add to these lists in the template, never per site. Per-site exceptions
 * (e.g. a brand name) go in client.config.ts under copyLint.allow.
 */

export const BANNED_PHRASES = [
  "unlock",
  "unleash",
  "elevate",
  "seamless",
  "seamlessly",
  "tailored solutions",
  "in today's fast-paced world",
  "in today's digital age",
  "take your business to the next level",
  "to the next level",
  "game-changer",
  "game changer",
  "cutting-edge",
  "best-in-class",
  "world-class",
  "synergy",
  "leverage",
  "empower",
  "delve",
  "revolutionise",
  "supercharge",
  "look no further",
  "one-stop shop",
  "we pride ourselves",
  "your trusted partner",
  "harness the power",
  "embark on",
  "navigate the complexities",
];

/** American spelling -> British. Matched as whole words, case-insensitive. */
export const AMERICAN_SPELLINGS: Record<string, string> = {
  color: "colour",
  colors: "colours",
  colored: "coloured",
  colorful: "colourful",
  favor: "favour",
  favorite: "favourite",
  favorites: "favourites",
  honor: "honour",
  labor: "labour",
  neighbor: "neighbour",
  neighborhood: "neighbourhood",
  behavior: "behaviour",
  flavor: "flavour",
  humor: "humour",
  rumor: "rumour",
  savior: "saviour",
  center: "centre",
  centers: "centres",
  theater: "theatre",
  fiber: "fibre",
  liter: "litre",
  catalog: "catalogue",
  dialog: "dialogue",
  analyze: "analyse",
  analyzed: "analysed",
  organize: "organise",
  organized: "organised",
  organization: "organisation",
  organizations: "organisations",
  realize: "realise",
  recognize: "recognise",
  optimize: "optimise",
  optimized: "optimised",
  optimization: "optimisation",
  customize: "customise",
  customized: "customised",
  prioritize: "prioritise",
  specialize: "specialise",
  specialized: "specialised",
  specializing: "specialising",
  apologize: "apologise",
  minimize: "minimise",
  maximize: "maximise",
  personalize: "personalise",
  personalized: "personalised",
  standardize: "standardise",
  utilize: "utilise",
  emphasize: "emphasise",
  summarize: "summarise",
  defense: "defence",
  offense: "offence",
  license: "licence (noun) or license (verb): check",
  practice: "practise (verb) or practice (noun): check",
  traveling: "travelling",
  traveled: "travelled",
  canceled: "cancelled",
  modeling: "modelling",
  labeled: "labelled",
  jewelry: "jewellery",
  gray: "grey",
  enroll: "enrol",
  fulfill: "fulfil",
  aluminum: "aluminium",
  mom: "mum",
  cozy: "cosy",
  donut: "doughnut",
  airplane: "aeroplane",
  check: "cheque (payment) or check: confirm",
  tire: "tyre (wheel) or tire: confirm",
  curb: "kerb (road) or curb: confirm",
};

/** Words that are sometimes correct in British English: reported as warnings, not failures. */
export const AMBIGUOUS = new Set(["license", "practice", "check", "tire", "curb"]);
